### ISSUE TITLE
Spell mistake in CardSortActivity.py

### ISSUE THREAD

**Issue by Aniket21mathur** [sugarlabs/cardsort#12]

**Comment by Aniket21mathur** [comment]
There is a spell mistake CardSortActivity.py line 36
PATH = '/org/augarlabs/CardSortActivity'
Instead of "a" it should be "s"

**Comment by quozl** [comment]
Please don't raise an issue for a problem you are already planning to fix in a pull request.  Just make the pull request.  Thanks.

**Comment by Aniket21mathur** [comment]
Thanks @quozl I will take care of that :sweat_smile:
