### ISSUE TITLE
Fix license

### ISSUE THREAD

**Issue by quozl** [sugarlabs/cardsort#8]
* [ ] add GPLv3 full text to COPYING; at the moment it contains an edited short text,
* [ ] repair the GPLv3+ short text in each source file; at the moment they are not the standard short text,
* [ ] use multiple-license-scenario in metadata or relicense sprites.py; it is not GPLv3+,

and also in passing;

* [ ] remove MANIFEST; it is deprecated,

**Comment by chimosky** [comment]
Changes made in 01acca2
- [x]  add GPLv3 full text to COPYING; at the moment it contains an edited short text,
- [x]  repair the GPLv3+ short text in each source file; at the moment they are not the standard short text,
- [x]  use multiple-license-scenario in metadata or relicense sprites.py; it is not GPLv3+,
- [x]  remove MANIFEST; it is deprecated,

**Comment by quozl** [comment]
Fixed by 55624ebf501deb5fcc4924a33000098c84614ebd and ca23b738fee18e79b886757cc941b27e0efc9ffb.
