### ISSUE TITLE
Size for display

### ISSUE THREAD

**Issue by quozl** [sugarlabs/cardsort#9]
Activity does not fit to display size.  For example, on an Ubuntu 18.04 KVM with 1024x768 4:3 display;

![screenshot_ubb_2018-05-08_10 23 38](https://user-images.githubusercontent.com/2936481/39731254-e84813d0-52a9-11e8-90da-773cc94f2817.png)

For the activity to fit to display size;
* at minimum, the orange section should be centred in the window,
* at best, the orange section should be enlarged to cover more pixels within the window.

The orange section includes the contents of the section.

**Comment by Aniket21mathur** [comment]
Thanks @quozl I misunderstood the issue, thanks for clarifying!

**Comment by JuiP** [comment]
@quozl move to project Display resolution detection
